/**
 * Stocks
 * <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: equibles@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CashFlowStatement model module.
* @module model/CashFlowStatement
* @version v1
*/
export default class CashFlowStatement {
    /**
    * Constructs a new <code>CashFlowStatement</code>.
    * @alias module:model/CashFlowStatement
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CashFlowStatement</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CashFlowStatement} obj Optional instance to populate.
    * @return {module:model/CashFlowStatement} The populated <code>CashFlowStatement</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CashFlowStatement();
                        
            
            if (data.hasOwnProperty('operatingCashFlow')) {
                obj['operatingCashFlow'] = ApiClient.convertToType(data['operatingCashFlow'], 'Number');
            }
            if (data.hasOwnProperty('paymentsForOperatingActivities')) {
                obj['paymentsForOperatingActivities'] = ApiClient.convertToType(data['paymentsForOperatingActivities'], 'Number');
            }
            if (data.hasOwnProperty('proceedsFromOperatingActivities')) {
                obj['proceedsFromOperatingActivities'] = ApiClient.convertToType(data['proceedsFromOperatingActivities'], 'Number');
            }
            if (data.hasOwnProperty('changeInOperatingLiabilities')) {
                obj['changeInOperatingLiabilities'] = ApiClient.convertToType(data['changeInOperatingLiabilities'], 'Number');
            }
            if (data.hasOwnProperty('changeInOperatingAssets')) {
                obj['changeInOperatingAssets'] = ApiClient.convertToType(data['changeInOperatingAssets'], 'Number');
            }
            if (data.hasOwnProperty('depreciationDepletionAndAmortization')) {
                obj['depreciationDepletionAndAmortization'] = ApiClient.convertToType(data['depreciationDepletionAndAmortization'], 'Number');
            }
            if (data.hasOwnProperty('capitalExpenditures')) {
                obj['capitalExpenditures'] = ApiClient.convertToType(data['capitalExpenditures'], 'Number');
            }
            if (data.hasOwnProperty('changeInReceivables')) {
                obj['changeInReceivables'] = ApiClient.convertToType(data['changeInReceivables'], 'Number');
            }
            if (data.hasOwnProperty('changeInInventory')) {
                obj['changeInInventory'] = ApiClient.convertToType(data['changeInInventory'], 'Number');
            }
            if (data.hasOwnProperty('profitLoss')) {
                obj['profitLoss'] = ApiClient.convertToType(data['profitLoss'], 'Number');
            }
            if (data.hasOwnProperty('investments')) {
                obj['investments'] = ApiClient.convertToType(data['investments'], 'Number');
            }
            if (data.hasOwnProperty('cashFlowFromInvestment')) {
                obj['cashFlowFromInvestment'] = ApiClient.convertToType(data['cashFlowFromInvestment'], 'Number');
            }
            if (data.hasOwnProperty('cashFlowFromFinancing')) {
                obj['cashFlowFromFinancing'] = ApiClient.convertToType(data['cashFlowFromFinancing'], 'Number');
            }
            if (data.hasOwnProperty('proceedsFromRepaymentsOfShortTermDebt')) {
                obj['proceedsFromRepaymentsOfShortTermDebt'] = ApiClient.convertToType(data['proceedsFromRepaymentsOfShortTermDebt'], 'Number');
            }
            if (data.hasOwnProperty('paymentsForRepurchaseOfCommonStock')) {
                obj['paymentsForRepurchaseOfCommonStock'] = ApiClient.convertToType(data['paymentsForRepurchaseOfCommonStock'], 'Number');
            }
            if (data.hasOwnProperty('paymentsForRepurchaseOfEquity')) {
                obj['paymentsForRepurchaseOfEquity'] = ApiClient.convertToType(data['paymentsForRepurchaseOfEquity'], 'Number');
            }
            if (data.hasOwnProperty('paymentsForRepurchaseOfPreferredStock')) {
                obj['paymentsForRepurchaseOfPreferredStock'] = ApiClient.convertToType(data['paymentsForRepurchaseOfPreferredStock'], 'Number');
            }
            if (data.hasOwnProperty('dividendPayout')) {
                obj['dividendPayout'] = ApiClient.convertToType(data['dividendPayout'], 'Number');
            }
            if (data.hasOwnProperty('dividendPayoutCommonStock')) {
                obj['dividendPayoutCommonStock'] = ApiClient.convertToType(data['dividendPayoutCommonStock'], 'Number');
            }
            if (data.hasOwnProperty('dividendPayoutPreferredStock')) {
                obj['dividendPayoutPreferredStock'] = ApiClient.convertToType(data['dividendPayoutPreferredStock'], 'Number');
            }
            if (data.hasOwnProperty('proceedsFromIssuanceOfCommonStock')) {
                obj['proceedsFromIssuanceOfCommonStock'] = ApiClient.convertToType(data['proceedsFromIssuanceOfCommonStock'], 'Number');
            }
            if (data.hasOwnProperty('proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet')) {
                obj['proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet'] = ApiClient.convertToType(data['proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet'], 'Number');
            }
            if (data.hasOwnProperty('proceedsFromIssuanceOfPreferredStock')) {
                obj['proceedsFromIssuanceOfPreferredStock'] = ApiClient.convertToType(data['proceedsFromIssuanceOfPreferredStock'], 'Number');
            }
            if (data.hasOwnProperty('proceedsFromRepurchaseOfEquity')) {
                obj['proceedsFromRepurchaseOfEquity'] = ApiClient.convertToType(data['proceedsFromRepurchaseOfEquity'], 'Number');
            }
            if (data.hasOwnProperty('proceedsFromSaleOfTreasuryStock')) {
                obj['proceedsFromSaleOfTreasuryStock'] = ApiClient.convertToType(data['proceedsFromSaleOfTreasuryStock'], 'Number');
            }
            if (data.hasOwnProperty('changeInCashAndCashEquivalents')) {
                obj['changeInCashAndCashEquivalents'] = ApiClient.convertToType(data['changeInCashAndCashEquivalents'], 'Number');
            }
            if (data.hasOwnProperty('changeInExchangeRate')) {
                obj['changeInExchangeRate'] = ApiClient.convertToType(data['changeInExchangeRate'], 'Number');
            }
            if (data.hasOwnProperty('netIncome')) {
                obj['netIncome'] = ApiClient.convertToType(data['netIncome'], 'Number');
            }
            if (data.hasOwnProperty('netBorrowings')) {
                obj['netBorrowings'] = ApiClient.convertToType(data['netBorrowings'], 'Number');
            }
            if (data.hasOwnProperty('changeInWorkingCapital')) {
                obj['changeInWorkingCapital'] = ApiClient.convertToType(data['changeInWorkingCapital'], 'Number');
            }
            if (data.hasOwnProperty('otherNonCashItems')) {
                obj['otherNonCashItems'] = ApiClient.convertToType(data['otherNonCashItems'], 'Number');
            }
            if (data.hasOwnProperty('freeCashFlow')) {
                obj['freeCashFlow'] = ApiClient.convertToType(data['freeCashFlow'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} operatingCashFlow
    */
    'operatingCashFlow' = undefined;
    /**
    * @member {Number} paymentsForOperatingActivities
    */
    'paymentsForOperatingActivities' = undefined;
    /**
    * @member {Number} proceedsFromOperatingActivities
    */
    'proceedsFromOperatingActivities' = undefined;
    /**
    * @member {Number} changeInOperatingLiabilities
    */
    'changeInOperatingLiabilities' = undefined;
    /**
    * @member {Number} changeInOperatingAssets
    */
    'changeInOperatingAssets' = undefined;
    /**
    * @member {Number} depreciationDepletionAndAmortization
    */
    'depreciationDepletionAndAmortization' = undefined;
    /**
    * @member {Number} capitalExpenditures
    */
    'capitalExpenditures' = undefined;
    /**
    * @member {Number} changeInReceivables
    */
    'changeInReceivables' = undefined;
    /**
    * @member {Number} changeInInventory
    */
    'changeInInventory' = undefined;
    /**
    * @member {Number} profitLoss
    */
    'profitLoss' = undefined;
    /**
    * @member {Number} investments
    */
    'investments' = undefined;
    /**
    * @member {Number} cashFlowFromInvestment
    */
    'cashFlowFromInvestment' = undefined;
    /**
    * @member {Number} cashFlowFromFinancing
    */
    'cashFlowFromFinancing' = undefined;
    /**
    * @member {Number} proceedsFromRepaymentsOfShortTermDebt
    */
    'proceedsFromRepaymentsOfShortTermDebt' = undefined;
    /**
    * @member {Number} paymentsForRepurchaseOfCommonStock
    */
    'paymentsForRepurchaseOfCommonStock' = undefined;
    /**
    * @member {Number} paymentsForRepurchaseOfEquity
    */
    'paymentsForRepurchaseOfEquity' = undefined;
    /**
    * @member {Number} paymentsForRepurchaseOfPreferredStock
    */
    'paymentsForRepurchaseOfPreferredStock' = undefined;
    /**
    * @member {Number} dividendPayout
    */
    'dividendPayout' = undefined;
    /**
    * @member {Number} dividendPayoutCommonStock
    */
    'dividendPayoutCommonStock' = undefined;
    /**
    * @member {Number} dividendPayoutPreferredStock
    */
    'dividendPayoutPreferredStock' = undefined;
    /**
    * @member {Number} proceedsFromIssuanceOfCommonStock
    */
    'proceedsFromIssuanceOfCommonStock' = undefined;
    /**
    * @member {Number} proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet
    */
    'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet' = undefined;
    /**
    * @member {Number} proceedsFromIssuanceOfPreferredStock
    */
    'proceedsFromIssuanceOfPreferredStock' = undefined;
    /**
    * @member {Number} proceedsFromRepurchaseOfEquity
    */
    'proceedsFromRepurchaseOfEquity' = undefined;
    /**
    * @member {Number} proceedsFromSaleOfTreasuryStock
    */
    'proceedsFromSaleOfTreasuryStock' = undefined;
    /**
    * @member {Number} changeInCashAndCashEquivalents
    */
    'changeInCashAndCashEquivalents' = undefined;
    /**
    * @member {Number} changeInExchangeRate
    */
    'changeInExchangeRate' = undefined;
    /**
    * @member {Number} netIncome
    */
    'netIncome' = undefined;
    /**
    * @member {Number} netBorrowings
    */
    'netBorrowings' = undefined;
    /**
    * @member {Number} changeInWorkingCapital
    */
    'changeInWorkingCapital' = undefined;
    /**
    * @member {Number} otherNonCashItems
    */
    'otherNonCashItems' = undefined;
    /**
    * @member {Number} freeCashFlow
    */
    'freeCashFlow' = undefined;




}
