/*
 * Stocks
 * <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: equibles@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {DividendsResponse} from '../model/DividendsResponse';
import {FiscalPeriod} from '../model/FiscalPeriod';
import {FundamentalsResponse} from '../model/FundamentalsResponse';

/**
* Fundamentals service.
* @module api/FundamentalsApi
* @version v1
*/
export class FundamentalsApi {

    /**
    * Constructs a new FundamentalsApi. 
    * @alias module:api/FundamentalsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get the dividends for a given stock.
     * @param {String} fullTicker The fully qualified ticker of the stock. Example: AAPL.XNAS
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page The number of the page to request. (default to <.>)
     * @param {Number} opts.pageSize The number of elements in each page. Max value: 1000. (default to <.>)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DividendsResponse} and HTTP response
     */
    dividendsWithHttpInfo(fullTicker, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'fullTicker' is set
      if (fullTicker === undefined || fullTicker === null) {
        throw new Error("Missing the required parameter 'fullTicker' when calling dividends");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'fullTicker': fullTicker,'page': opts['page'],'pageSize': opts['pageSize']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Query String'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = DividendsResponse;

      return this.apiClient.callApi(
        '/stocks/fundamentals/dividends', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get the dividends for a given stock.
     * @param {<&vendorExtensions.x-jsdoc-type>} fullTicker The fully qualified ticker of the stock. Example: AAPL.XNAS
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page The number of the page to request. (default to <.>)
     * @param {Number} opts.pageSize The number of elements in each page. Max value: 1000. (default to <.>)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DividendsResponse}
     */
    dividends(fullTicker, opts) {
      return this.dividendsWithHttpInfo(fullTicker, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get the financial statements for a given stock.
     * Returns a list of fully qualified ticker names. A fully qualified ticker has the following structure: [Ticker].[ExchangeMic] Example: AAPL.XNAS.
     * @param {String} fullTicker The fully qualified ticker of the stock. Example: AAPL.XNAS
     * @param {Number} year The year of the report.
     * @param {module:model/FiscalPeriod} fiscalPeriod The fiscal period of the report.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page The number of the page to request. (default to <.>)
     * @param {Number} opts.pageSize The number of elements in each page. Max value: 50. (default to <.>)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/FundamentalsResponse} and HTTP response
     */
    financialReportsWithHttpInfo(fullTicker, year, fiscalPeriod, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'fullTicker' is set
      if (fullTicker === undefined || fullTicker === null) {
        throw new Error("Missing the required parameter 'fullTicker' when calling financialReports");
      }
      // verify the required parameter 'year' is set
      if (year === undefined || year === null) {
        throw new Error("Missing the required parameter 'year' when calling financialReports");
      }
      // verify the required parameter 'fiscalPeriod' is set
      if (fiscalPeriod === undefined || fiscalPeriod === null) {
        throw new Error("Missing the required parameter 'fiscalPeriod' when calling financialReports");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'fullTicker': fullTicker,'year': year,'fiscalPeriod': fiscalPeriod,'page': opts['page'],'pageSize': opts['pageSize']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Query String'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = FundamentalsResponse;

      return this.apiClient.callApi(
        '/stocks/fundamentals/financialreports', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get the financial statements for a given stock.
     * Returns a list of fully qualified ticker names. A fully qualified ticker has the following structure: [Ticker].[ExchangeMic] Example: AAPL.XNAS.
     * @param {<&vendorExtensions.x-jsdoc-type>} fullTicker The fully qualified ticker of the stock. Example: AAPL.XNAS
     * @param {<&vendorExtensions.x-jsdoc-type>} year The year of the report.
     * @param {<&vendorExtensions.x-jsdoc-type>} fiscalPeriod The fiscal period of the report.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page The number of the page to request. (default to <.>)
     * @param {Number} opts.pageSize The number of elements in each page. Max value: 50. (default to <.>)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/FundamentalsResponse}
     */
    financialReports(fullTicker, year, fiscalPeriod, opts) {
      return this.financialReportsWithHttpInfo(fullTicker, year, fiscalPeriod, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }

}