/*
 * Stocks
 * <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: equibles@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AssetType} from './model/AssetType';
import {BalanceSheet} from './model/BalanceSheet';
import {CashFlowStatement} from './model/CashFlowStatement';
import {CurrenciesResponse} from './model/CurrenciesResponse';
import {Currency} from './model/Currency';
import {Dividend} from './model/Dividend';
import {DividendsResponse} from './model/DividendsResponse';
import {Exchange} from './model/Exchange';
import {ExchangesResponse} from './model/ExchangesResponse';
import {FinancialAssetsResponse} from './model/FinancialAssetsResponse';
import {FinancialReport} from './model/FinancialReport';
import {FiscalPeriod} from './model/FiscalPeriod';
import {FundamentalsResponse} from './model/FundamentalsResponse';
import {Image} from './model/Image';
import {IncomeStatement} from './model/IncomeStatement';
import {Industry} from './model/Industry';
import {MetricNullablePointsResponse} from './model/MetricNullablePointsResponse';
import {News} from './model/News';
import {NewsResponse} from './model/NewsResponse';
import {NullablePoint} from './model/NullablePoint';
import {Officer} from './model/Officer';
import {OfficersResponse} from './model/OfficersResponse';
import {Performance} from './model/Performance';
import {PerformanceResponse} from './model/PerformanceResponse';
import {Price} from './model/Price';
import {PricesResponse} from './model/PricesResponse';
import {Publisher} from './model/Publisher';
import {PublishersResponse} from './model/PublishersResponse';
import {Recommendation} from './model/Recommendation';
import {ResponseStatus} from './model/ResponseStatus';
import {ScreenerRequest} from './model/ScreenerRequest';
import {Sector} from './model/Sector';
import {SectorsResponse} from './model/SectorsResponse';
import {SplitsResponse} from './model/SplitsResponse';
import {StockProfile} from './model/StockProfile';
import {StockProfileResponse} from './model/StockProfileResponse';
import {StockProfilesResponse} from './model/StockProfilesResponse';
import {StockSplit} from './model/StockSplit';
import {Transaction} from './model/Transaction';
import {TransactionType} from './model/TransactionType';
import {TransactionsResponse} from './model/TransactionsResponse';
import {ExchangesApi} from './api/ExchangesApi';
import {FundamentalsApi} from './api/FundamentalsApi';
import {MetricsApi} from './api/MetricsApi';
import {NewsApi} from './api/NewsApi';
import {PerformanceApi} from './api/PerformanceApi';
import {PricesApi} from './api/PricesApi';
import {SectorsApi} from './api/SectorsApi';
import {StocksApi} from './api/StocksApi';
import {TransactionsApi} from './api/TransactionsApi';

/**
* h3Authenticationh3____________________You_need_to_authenticate_to_use_this_API_____________________To_authenticate_click_on_the_Authorize_button_and_do_one_of_the_following_steps_br_____________________1__Send_your_API_key_in_the_headers_of_the_request_by_typing_Bearer_my_key_on_the_Bearer_authorization_scheme_br_____________________2__Send_your_API_key_on_the_ApiKey_query_string_parameter__To_do_this_type_your_API_key_in_the_Query_String_authorization_scheme_br_____________________Both_methods_are_equally_valid__We_offer_both_options_so_that_you_can_use_the_method_that_is_easier_to_use_in_your_application_br_____________________br_____________________h3API_limitsh3____________________Your_API_key_may_be_subject_to_dailyhourly_limits__To_know_how_much_requests_you_have_left_look_at_the_following_headers_in_the_response_br_____________________1__strongx_ratelimit_limitstrong___The_total_number_of_requests_that_you_are_allowed_to_make_in_a_given_period__hourday______________________2__strongx_ratelimit_remainingstrong___The_number_of_remaining_requests_that_you_can_perform_in_the_current_period_br_____________________3__strongx_ratelimit_resetstrong___The_number_of_seconds_until_the_current_period_resets_br_____________________br_____________________h3Suggestionsh3____________________You_dont_need_to_implement_the_whole_API_by_hand_in_your_programming_language_of_choice_br_____________________Since_this_API_has_an_OpenAPI_specification_you_can_use_____________________a_hrefhttpsgithub_comswagger_apiswagger_codegen_target_blankSwagger_Generatora_____________________to_automatically_generate_client_stubs_for_more_than_30_programming_languages_____________________br_____________________br_____________________You_dont_have_an_API_key_a_hrefhttpswww_equibles_comapipricing_target_blankGet_one_for_free_here_a.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var EquiblesStocks = require('index'); // See note below*.
* var xxxSvc = new EquiblesStocks.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new EquiblesStocks.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new EquiblesStocks.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new EquiblesStocks.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AssetType model constructor.
     * @property {module:model/AssetType}
     */
    AssetType,

    /**
     * The BalanceSheet model constructor.
     * @property {module:model/BalanceSheet}
     */
    BalanceSheet,

    /**
     * The CashFlowStatement model constructor.
     * @property {module:model/CashFlowStatement}
     */
    CashFlowStatement,

    /**
     * The CurrenciesResponse model constructor.
     * @property {module:model/CurrenciesResponse}
     */
    CurrenciesResponse,

    /**
     * The Currency model constructor.
     * @property {module:model/Currency}
     */
    Currency,

    /**
     * The Dividend model constructor.
     * @property {module:model/Dividend}
     */
    Dividend,

    /**
     * The DividendsResponse model constructor.
     * @property {module:model/DividendsResponse}
     */
    DividendsResponse,

    /**
     * The Exchange model constructor.
     * @property {module:model/Exchange}
     */
    Exchange,

    /**
     * The ExchangesResponse model constructor.
     * @property {module:model/ExchangesResponse}
     */
    ExchangesResponse,

    /**
     * The FinancialAssetsResponse model constructor.
     * @property {module:model/FinancialAssetsResponse}
     */
    FinancialAssetsResponse,

    /**
     * The FinancialReport model constructor.
     * @property {module:model/FinancialReport}
     */
    FinancialReport,

    /**
     * The FiscalPeriod model constructor.
     * @property {module:model/FiscalPeriod}
     */
    FiscalPeriod,

    /**
     * The FundamentalsResponse model constructor.
     * @property {module:model/FundamentalsResponse}
     */
    FundamentalsResponse,

    /**
     * The Image model constructor.
     * @property {module:model/Image}
     */
    Image,

    /**
     * The IncomeStatement model constructor.
     * @property {module:model/IncomeStatement}
     */
    IncomeStatement,

    /**
     * The Industry model constructor.
     * @property {module:model/Industry}
     */
    Industry,

    /**
     * The MetricNullablePointsResponse model constructor.
     * @property {module:model/MetricNullablePointsResponse}
     */
    MetricNullablePointsResponse,

    /**
     * The News model constructor.
     * @property {module:model/News}
     */
    News,

    /**
     * The NewsResponse model constructor.
     * @property {module:model/NewsResponse}
     */
    NewsResponse,

    /**
     * The NullablePoint model constructor.
     * @property {module:model/NullablePoint}
     */
    NullablePoint,

    /**
     * The Officer model constructor.
     * @property {module:model/Officer}
     */
    Officer,

    /**
     * The OfficersResponse model constructor.
     * @property {module:model/OfficersResponse}
     */
    OfficersResponse,

    /**
     * The Performance model constructor.
     * @property {module:model/Performance}
     */
    Performance,

    /**
     * The PerformanceResponse model constructor.
     * @property {module:model/PerformanceResponse}
     */
    PerformanceResponse,

    /**
     * The Price model constructor.
     * @property {module:model/Price}
     */
    Price,

    /**
     * The PricesResponse model constructor.
     * @property {module:model/PricesResponse}
     */
    PricesResponse,

    /**
     * The Publisher model constructor.
     * @property {module:model/Publisher}
     */
    Publisher,

    /**
     * The PublishersResponse model constructor.
     * @property {module:model/PublishersResponse}
     */
    PublishersResponse,

    /**
     * The Recommendation model constructor.
     * @property {module:model/Recommendation}
     */
    Recommendation,

    /**
     * The ResponseStatus model constructor.
     * @property {module:model/ResponseStatus}
     */
    ResponseStatus,

    /**
     * The ScreenerRequest model constructor.
     * @property {module:model/ScreenerRequest}
     */
    ScreenerRequest,

    /**
     * The Sector model constructor.
     * @property {module:model/Sector}
     */
    Sector,

    /**
     * The SectorsResponse model constructor.
     * @property {module:model/SectorsResponse}
     */
    SectorsResponse,

    /**
     * The SplitsResponse model constructor.
     * @property {module:model/SplitsResponse}
     */
    SplitsResponse,

    /**
     * The StockProfile model constructor.
     * @property {module:model/StockProfile}
     */
    StockProfile,

    /**
     * The StockProfileResponse model constructor.
     * @property {module:model/StockProfileResponse}
     */
    StockProfileResponse,

    /**
     * The StockProfilesResponse model constructor.
     * @property {module:model/StockProfilesResponse}
     */
    StockProfilesResponse,

    /**
     * The StockSplit model constructor.
     * @property {module:model/StockSplit}
     */
    StockSplit,

    /**
     * The Transaction model constructor.
     * @property {module:model/Transaction}
     */
    Transaction,

    /**
     * The TransactionType model constructor.
     * @property {module:model/TransactionType}
     */
    TransactionType,

    /**
     * The TransactionsResponse model constructor.
     * @property {module:model/TransactionsResponse}
     */
    TransactionsResponse,

    /**
    * The ExchangesApi service constructor.
    * @property {module:api/ExchangesApi}
    */
    ExchangesApi,

    /**
    * The FundamentalsApi service constructor.
    * @property {module:api/FundamentalsApi}
    */
    FundamentalsApi,

    /**
    * The MetricsApi service constructor.
    * @property {module:api/MetricsApi}
    */
    MetricsApi,

    /**
    * The NewsApi service constructor.
    * @property {module:api/NewsApi}
    */
    NewsApi,

    /**
    * The PerformanceApi service constructor.
    * @property {module:api/PerformanceApi}
    */
    PerformanceApi,

    /**
    * The PricesApi service constructor.
    * @property {module:api/PricesApi}
    */
    PricesApi,

    /**
    * The SectorsApi service constructor.
    * @property {module:api/SectorsApi}
    */
    SectorsApi,

    /**
    * The StocksApi service constructor.
    * @property {module:api/StocksApi}
    */
    StocksApi,

    /**
    * The TransactionsApi service constructor.
    * @property {module:api/TransactionsApi}
    */
    TransactionsApi
};
